version: '3'
services:
  testing-new:
    container_name: be-testing-new
    build: .
    ports:
      - "49160:3000"
    stdin_open: true
    environment:
      DB_USER: postgres
      DB_HOST: host.docker.internal
      DB_DATABASE: Sicana_Services
      DB_PASSWORD: postgres
    restart: always
    networks:
      - networks-testing-new
    command: npm start
networks:
  networks-testing-new:
  ipam:
    driver: default
    